#= Map as soon as possible, in case of configuration errors
map global user ,     ': edit "%val{config}/kakrc"<ret>'   -docstring 'Edit config'
map global user <a-,> ': source "%val{config}/kakrc"<ret>' -docstring 'Source config'
map global user /     ': comment-line<ret>'  -docstring 'comment line'
map global user <a-/> ': comment-block<ret>' -docstring 'comment block'

#= Plugins
source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/smarttab.kak" defer smarttab %{
    # when `backspace' is pressed, 4 spaces are deleted at once
    set-option global softtabstop 4
    # configure text that is being used to represent curent active mode
    set-option global smarttab_expandtab_mode_name   'exp'
    set-option global smarttab_noexpandtab_mode_name 'noexp'
    set-option global smarttab_smarttab_mode_name    'smart'
} config %{
    hook global WinSetOption filetype=.* expandtab
    # # these languages will use `expandtab' behavior
    # hook global WinSetOption filetype=(rust|markdown|kak|lisp|scheme|sh|perl) expandtab
    # # these languages will use `noexpandtab' behavior
    # hook global WinSetOption filetype=(makefile|gas) noexpandtab
    # # these languages will use `smarttab' behavior
    # hook global WinSetOption filetype=(c|cpp) smarttab
}

plug "alexherbo2/yank-ring.kak" config %{
    map global user y '<esc>: yank-ring<ret>' -docstring "yank-ring"
}

plug "andreyorst/fzf.kak" config %{
    # map global normal <minus> ': fzf-mode<ret>'

    require-module fzf
    map global user 'f'     '<esc>: fzf-file<ret>'                        -docstring "open file"
    map global user 'b'     '<esc>: fzf-buffer<ret>'                      -docstring "open buffer"
    map global user '<a-b>' '<esc>: fzf-delete-buffer<ret>'               -docstring "delete buffer"
    map global user 'g'     '<esc>: fzf-grep<ret>'                             -docstring 'grep file contents recursively'
    map global user 's'     '<esc>: fzf-buffer-search<ret>'               -docstring "search in buffer"
    map global user 'v'     '<esc>: require-module fzf_vcs; fzf-vcs<ret>' -docstring "edit file from vcs repo"
    map global user '<a-v>' '<esc>: fzf-vcs-mode<ret>'                    -docstring "switch to vcs selection mode"
    map global user 'p'     '<esc>: fzf-project<ret>'                     -docstring "open project"
    map global user 'c'     '<esc>: fzf-cd<ret>'                          -docstring "change directory"
    # doesn't work
    # map global user 'y'   '<esc>: fzf-yank-ring<ret>'                   -docstring "open yank-ring"
} defer fzf %{
    set fzf_implementation skim
}

# Don't know how to disable default mappings
# plug "alexherbo2/phantom.kak" config %{
#     map global user H ': phantom-append<ret>'
#     map global user h ': phantom-restore; phantom-clear<ret>'
#     map global user <a-h> ': phantom-clear<ret>'
#     # Iterate phantom selections in insert mode.
#     map global insert <a-i> '<esc>: phantom-append<ret><space>i'
#     map global insert <a-a> '<esc>: phantom-append<ret><space>a'
#     map global insert <a-n> '<esc>: phantom-append; phantom-restore<ret>)<space>i'
#     map global insert <a-p> '<esc>: phantom-append; phantom-restore<ret>(<space>i'
# }

# plug "occivink/kakoune-phantom-selection" config %{
#     map global user f     ": phantom-selection-add-selection<ret>"
#     map global user F     ": phantom-selection-select-all; phantom-selection-clear<ret>"
#     map global user <a-f> ": phantom-selection-iterate-next<ret>"
#     map global user <a-F> ": phantom-selection-iterate-prev<ret>"
# }

plug "danr/kakoune-easymotion" config %{
    # map global normal <a-g> ':enter-user-mode<space>easymotion<ret>'
    declare-user-mode jump
    map global jump c '<esc>: easy-motion-char<ret>'      -docstring 'to char'
    map global jump w '<esc>: easy-motion-word<ret>'      -docstring 'to word'
    map global jump g '<esc>: easy-motion-line<ret>'      -docstring 'to line'
    map global user j ': enter-user-mode<space>jump<ret>' -docstring 'jump'
}

plug "lePerdu/kakboard" %{
    # hook global WinCreate .* %{ kakboard-enable }
    map global user t ': kakboard-toggle<ret>' -docstring 'Kakboard toggle'
    # map global user y ': kakboard-push-clipboard<ret>' -d ocstring 'Push clipboard'
    # map global user p ': kakboard-pull-clipboard<ret>' -docst ring 'Push clipboard'
}

plug 'delapouite/kakoune-mirror' %{
  map global user m ': enter-user-mode -lock mirror<ret>' -docstring 'mirror'
}

plug "alexherbo2/prelude.kak"
plug "alexherbo2/connect.kak" config %{
    def connect-nnn %{
    	connect-terminal sh -c '(NNN_OPENER=edit nnn; NNN_OPENER=edit bash)'
    }
    map global user n ': connect-nnn<ret>' -docstring 'nnn'
}

plug "ul/kak-lsp" do %{
    # Install only when it doesn't exist.
    command -v kak-lsp >/dev/null 2>&1 || cargo install --locked --force --path .
} config %{
    set-option global lsp_server_configuration haxe.haxe.executable="haxe"

    # debug
    # set global lsp_cmd "kak-lsp -s %val{session} -vvv --log /tmp/kak-lsp.log"

    map global normal <minus> ':enter-user-mode<space>lsp<ret>'
    hook global WinSetOption filetype=(haxe) %{
        lsp-enable-window
    }
}

# plug "lenormf/kakoune-extra"

plug "occivink/kakoune-find"

plug "https://gitlab.com/Screwtapello/kakoune-inc-dec"


#= Trailing whitespace errors
# Fix trailing whitespace errors
define-command trailine-whitespace-errors-fix -docstring '
Removes trailing whitespace errors
' %{
    try %{
        execute-keys -draft \% s \h+$ <ret> d
    } catch %{
        echo "No trailing whitespace errors"
    }
}


# Show trailing white space errors (except in insert mode)
define-command trailing-whitespace-errors-show -docstring '
Shows trailing whitespace errors
' %{
    add-highlighter global/trailing-whitespace-error regex \h+$ 0:black,red
}
define-command trailing-whitespace-errors-hide -docstring '
Hide trailing whitespace errors
' %{
    remove-highlighter global/trailing-whitespace-error
}
trailing-whitespace-errors-show
hook global ModeChange push:normal:insert -group trailine-whitespace-errors trailing-whitespace-errors-hide
hook global ModeChange pop:insert:normal -group trailine-whitespace-errors trailing-whitespace-errors-show


#= Auto save
# TODO: It changes files - add some lineends, etc...
# - use draft to avoid clearing echo line, so for example ':echo abc' will be able to show its output
# hook global NormalIdle .* -group auto-save 'try %{ exec -draft :w<ret>}'
# hook global ModeChange pop:insert:normal -group auto-save 'try %{exec -draft :w<ret>}'

#= Options
# set-option global extra_word_chars '_' '-'

#= Mappings
declare-user-mode project
map global project <(> ' :bp<ret>'                   -docstring 'prev buffer'
map global project <)> ' :bn<ret>'                   -docstring 'next buffer'
map global project b   ' :make build:debug<ret>'     -docstring 'build debug'
map global project r   ' :make build:debug run<ret>' -docstring 'run debug'
map global normal <=>  ' :enter-user-mode<space>project<ret>'

#= Colorscheme
# colorscheme base16

#= Imports
source "%val{config}/filetype/haxe.kak"
source "%val{config}/filetype/cocoapods.kak"
source "%val{config}/filetype/gradle.kak"
source "%val{config}/filetype/makefile.kak"

# source "%val{config}/expand-tab.kak"

